name: Sync Labels & Milestones

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:

jobs:
  sync-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout org-utils repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Sync Labels & Milestones
        run: node sync-org-resources.js
        env:
          GH_TOKEN: ${{ secrets.LABEL_SYNC_TOKEN }}

      - name: Sync Issue Templates
        run: node sync-issue-templates.js
        env:
          GH_TOKEN: ${{ secrets.LABEL_SYNC_TOKEN }}