name: Sync Labels & Milestones

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Octokit
        run: npm install @octokit/rest

      - name: Run Sync Script
        env:
          GH_TOKEN: ${{ secrets.LABEL_SYNC_TOKEN }}
        run: node sync-org-resources.js
